//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanSPA.Demo.AngularJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string BodyText { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
